[package]
name = "app"
edition = "2021"
license = "CAL-1.0"
version.workspace = true

[dependencies]
lib = { path = "../lib" }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
