[package]
name = "flt_lib"
edition = "2021"
version.workspace = true
license.workspace = true

[dependencies]
tracing =  { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
clap = { workspace = true }

iroh = { version = "0.95.0", features = ["discovery-local-network"] }
irpc = { version = "0.11.0", features = ["derive", "rpc"] }
irpc-iroh = "0.11.0"
iroh-blobs = "0.97.0"
iroh-gossip = { version = "0.95.0", features = ["rpc"] }
iroh-docs = "0.95.0"

serde = "1.0.219"
serde_json = "1.0.143"
mid = { version = "4.0.0", features = ["serde"] }
os_info = { version = "3.12.0", features = ["serde"] }
platforms = { version = "3.6.0", features = ["serde"] }
better-commands = "1.0.2"
jsonpath-rust = "1.0.4"
ssh-key = { version = "0.6.7", features = ["ed25519", "encryption"] }
data-encoding = "2.9.0"
blake3 = "1.8.2"
url = "2.5.7"
bytes = "1.11.0"
futures-util = "0.3.31"

iroh-relay = { version = "0.95.0", features = [ "server", "test-utils" ], optional = true }
iroh-dns-server = { version = "0.95.0", optional = true}
tracing-test = { version = "0.2.5", features = ["no-env-filter"], optional = true}
criterion = { version = "0.7.0", features = ["async", "stable"], optional = true }
test-case = { version = "3.3.1", optional = true }
chrono = { version = "0.4.42", features = ["serde", "pure-rust-locales"] }
hkdf = "0.12.4"
linked-hash-map = { version = "0.5.6", features = ["serde", "serde_impl"] }
linked_hash_set = { version = "0.1.6", features = ["serde"] }
strum = { version = "0.27.2", features = ["derive", "strum_macros"] }
erased-serde = "0.4.9"

[dev-dependencies]
flt_lib = { path = ".", features = ["test"]}

[[bench]]
name = "echo_completes"
harness = false
required-features = ["test"]

[features]

default = []

test = [
    "iroh/test-utils",

    "dep:iroh-dns-server",
    "dep:iroh-relay",
    "dep:test-case",
    "dep:tracing-test",
    "dep:criterion",
]
